### ISSUE TITLE
[fish-deleter-master] is outdated and cannot be used anymore

### ISSUE THREAD

**Issue by mixxedxyz** [Lambda11/Fish-Deleter#4]
[13:33:37.034] [mods] ERROR: Module "Fish-Deleter-master" could not be loaded!
[13:33:37.035] [mods] ERROR: Please contact the module's author: https://discord.gg/659YbNY
[13:33:37.037] Error: [dispatch] [fish-deleter-master] hook: Error: version 1 of message (name: "S_ITEMLIST", code: 57287) is outdated and cannot be used anymore
    at Dispatch.createHook (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:247:27)
    at Dispatch.hook (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at new FishDeleter (C:\TeraToolbox\mods\Fish-Deleter-master\index.js:22:7)
    at ModuleManager.load (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:157:35)
    at C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)
    at Socket.<anonymous> (C:\TeraToolbox\bin\connectionManager.js:55:47)
    at Socket.emit (events.js:205:15)

**Comment by Lambda11** [comment]
fixed
